version: "3.7"

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ../ui/dist/go-backups-ui:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:12480:80"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  gobackups:
    image: gobackups-api:latest
    restart: unless-stopped
    volumes:
      - /:/host/ # use caution when mounting the host file system in a container
      - ./log.json:/log.json
      - ./config.yml:/config.yml
    ports:
      - "127.0.0.1:12403:12403"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
